"""Simple public API for the DDA host application."""

from .errors import (
    BoardError,
    BoardProtocolError,
    BoardRejectedError,
    BoardTimeoutError,
)
from .competition import (
    Bobine,
    Bridge,
    Capteur,
    CarteCompetition,
    CompetitionBoard,
    DefautEtagePuissance,
    DeviceMode,
    Direction,
    DonneesLancement,
    EtatLancement,
    EtatSysteme,
    EtalonnageCapteur,
    EvenementsCapteur,
    FrontCapteur,
    LaunchData,
    LaunchResult,
    LaunchStatus,
    LaunchTimingReport,
    LatenceCapteur,
    LatencyStatistics,
    RequestLatency,
    RequestEvent,
    RequestSnapshot,
    PowerStageFault,
    SensorCalibration,
    SensorChannel,
    SensorEdge,
    SensorEvents,
    SensorLatency,
    SensorNotification,
    SystemState,
    ModeCarte,
    NotificationCapteur,
    RapportTemporisationLancement,
    ResultatLancement,
    formaterRapportTemporisation,
    formatTimingReport,
    format_timing_report,
    plotLaunchResult,
    plot_launch_result,
    tracerResultatLancement,
)

ErreurCarte = BoardError
ErreurProtocoleCarte = BoardProtocolError
ErreurCommandeRejetee = BoardRejectedError
ErreurDelaiCarte = BoardTimeoutError

__all__ = [
    "BoardError",
    "BoardProtocolError",
    "BoardRejectedError",
    "BoardTimeoutError",
    "Bobine",
    "Bridge",
    "Capteur",
    "CarteCompetition",
    "CompetitionBoard",
    "DefautEtagePuissance",
    "DeviceMode",
    "Direction",
    "DonneesLancement",
    "ErreurCarte",
    "ErreurCommandeRejetee",
    "ErreurDelaiCarte",
    "ErreurProtocoleCarte",
    "EtatLancement",
    "EtatSysteme",
    "EtalonnageCapteur",
    "EvenementsCapteur",
    "FrontCapteur",
    "LaunchData",
    "LaunchResult",
    "LaunchStatus",
    "LaunchTimingReport",
    "LatenceCapteur",
    "LatencyStatistics",
    "RequestLatency",
    "RequestEvent",
    "RequestSnapshot",
    "PowerStageFault",
    "SensorCalibration",
    "SensorChannel",
    "SensorEdge",
    "SensorEvents",
    "SensorLatency",
    "SensorNotification",
    "SystemState",
    "ModeCarte",
    "NotificationCapteur",
    "RapportTemporisationLancement",
    "ResultatLancement",
    "formaterRapportTemporisation",
    "formatTimingReport",
    "format_timing_report",
    "plotLaunchResult",
    "plot_launch_result",
    "tracerResultatLancement",
]
