/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeMX
 * @brief     Bare-metal Newlib/Picolibc syscall and standard-I/O adapters.
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>


/* Variables */
// Weak character hooks let board code redirect console I/O without changing
// this generated C-library shim.
/**
 * @brief Write one character to the board console.
 * @param[in] ch Character value to write.
 * @return Hook-defined status, conventionally the written character.
 * @note A board-specific strong definition must be linked before use.
 */
extern int __io_putchar(int ch) __attribute__((weak));
/**
 * @brief Read one character from the board console.
 * @return Hook-defined character value.
 * @note A board-specific strong definition must be linked before use.
 */
extern int __io_getchar(void) __attribute__((weak));


// A bare-metal process has no inherited environment.
/// @brief Empty null-terminated environment vector for the C runtime.
char *__env[1] = { 0 };
/// @brief Process environment pointer exposed to the C library.
char **environ = __env;


/* Functions */
/// @brief Compatibility hook for semihosting runtimes; no setup is required.
void initialise_monitor_handles()
{
}

/**
 * @brief Return the single bare-metal process identifier.
 * @return Always 1.
 */
int _getpid(void)
{
  return 1;
}

/**
 * @brief Reject an unsupported request to signal a process.
 * @param[in] pid Process identifier; ignored.
 * @param[in] sig Signal number; ignored.
 * @return Always -1 with errno set to EINVAL.
 */
int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

/**
 * @brief Terminate execution in the absence of an operating system.
 * @param[in] status Process exit status forwarded to _kill().
 * @warning Never returns; the MCU waits for reset.
 */
void _exit (int status)
{
  _kill(status, -1);
  // Returning from exit has no operating-system destination; wait for reset.
  while (1) {}
}

/**
 * @brief Read bytes synchronously from the board console.
 * @param[in] file File descriptor; ignored because only one console exists.
 * @param[out] ptr Caller-owned destination buffer.
 * @param[in] len Number of bytes to read; must be non-negative.
 * @return len after all requested characters have been read.
 * @note This weak implementation blocks once per character in __io_getchar().
 */
__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = __io_getchar();
  }

  return len;
}

/**
 * @brief Write bytes synchronously to the board console.
 * @param[in] file File descriptor; ignored because only one console exists.
 * @param[in] ptr Caller-owned source buffer.
 * @param[in] len Number of bytes to write; must be non-negative.
 * @return len after all requested characters have been written.
 * @note This weak implementation writes once per character through __io_putchar().
 */
__attribute__((weak)) int _write(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    __io_putchar(*ptr++);
  }
  return len;
}

/**
 * @brief Reject closing a descriptor because no descriptor table exists.
 * @param[in] file File descriptor; ignored.
 * @return Always -1.
 */
int _close(int file)
{
  (void)file;
  return -1;
}


/**
 * @brief Describe every supported descriptor as a character device.
 * @param[in] file File descriptor; ignored.
 * @param[out] st Caller-owned status structure.
 * @return Always 0.
 */
int _fstat(int file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

/**
 * @brief Report every supported descriptor as a terminal.
 * @param[in] file File descriptor; ignored.
 * @return Always 1.
 */
int _isatty(int file)
{
  (void)file;
  return 1;
}

/**
 * @brief Accept a seek request without maintaining a file position.
 * @param[in] file File descriptor; ignored.
 * @param[in] ptr Requested offset; ignored.
 * @param[in] dir Seek origin; ignored.
 * @return Always 0.
 */
int _lseek(int file, int ptr, int dir)
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

/**
 * @brief Reject file creation or opening because no filesystem is mounted.
 * @param[in] path Requested path; ignored.
 * @param[in] flags Requested open flags; ignored.
 * @return Always -1.
 */
int _open(char *path, int flags, ...)
{
  (void)path;
  (void)flags;
  // No filesystem is mounted in this firmware.
  return -1;
}

/**
 * @brief Reject waiting for a child process.
 * @param[out] status Child status destination; ignored.
 * @return Always -1 with errno set to ECHILD.
 */
int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

/**
 * @brief Reject removing a filesystem entry.
 * @param[in] name Requested path; ignored.
 * @return Always -1 with errno set to ENOENT.
 */
int _unlink(char *name)
{
  (void)name;
  errno = ENOENT;
  return -1;
}

/**
 * @brief Report that process CPU-time accounting is unavailable.
 * @param[out] buf Timing destination; ignored.
 * @return Always -1.
 */
clock_t _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

/**
 * @brief Describe a requested path as a character device.
 * @param[in] file Requested path; ignored.
 * @param[out] st Caller-owned status structure.
 * @return Always 0.
 */
int _stat(const char *file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

/**
 * @brief Reject creation of a filesystem link.
 * @param[in] old Existing path; ignored.
 * @param[in] new Requested link path; ignored.
 * @return Always -1 with errno set to EMLINK.
 */
int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

/**
 * @brief Reject process creation on the bare-metal target.
 * @return Always -1 with errno set to EAGAIN.
 */
int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

/**
 * @brief Reject replacing the current process image.
 * @param[in] name Executable path; ignored.
 * @param[in] argv Argument vector; ignored.
 * @param[in] env Environment vector; ignored.
 * @return Always -1 with errno set to ENOMEM.
 */
int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}

// Picolibc-specific standard-stream adapters and syscall aliases.
#if defined(__PICOLIBC__)

/**
 * @brief Picolibc helper function to output a character to a FILE stream.
 *        This redirects the output to the low-level __io_putchar function.
 * @param c Character to write.
 * @param file FILE stream pointer (ignored).
 * @retval int The character written.
 */
static int starm_putc(char c, FILE *file)
{
	(void) file;
  __io_putchar(c);
	return c;
}

/**
 * @brief Picolibc helper function to input a character from a FILE stream.
 *        This redirects the input from the low-level __io_getchar function.
 * @param file FILE stream pointer (ignored).
 * @retval int The character read, cast to an unsigned char then int.
 */
static int starm_getc(FILE *file)
{
	unsigned char c;
	(void) file;
  c = __io_getchar();
	return c;
}

// Bind one bidirectional FILE object to the low-level character hooks.
static FILE __stdio = FDEV_SETUP_STREAM(starm_putc,
					starm_getc,
					NULL,
					_FDEV_SETUP_RW);

// stdin, stdout, and stderr intentionally share the same board console.
FILE *const stdin = &__stdio;
__strong_reference(stdin, stdout);
__strong_reference(stdin, stderr);

// Picolibc calls the POSIX spellings; alias them to the generated underscore
// syscall implementations without adding duplicate wrappers.
__strong_reference(_read, read);
__strong_reference(_write, write);
__strong_reference(_times, times);
__strong_reference(_execve, execve);
__strong_reference(_fork, fork);
__strong_reference(_link, link);
__strong_reference(_unlink, unlink);
__strong_reference(_stat, stat);
__strong_reference(_wait, wait);
__strong_reference(_open, open);
__strong_reference(_close, close);
__strong_reference(_lseek, lseek);
__strong_reference(_isatty, isatty);
__strong_reference(_fstat, fstat);
__strong_reference(_exit, exit);
__strong_reference(_kill, kill);
__strong_reference(_getpid, getpid);

#endif //__PICOLIBC__
