#pragma once

#include <cstdint>

namespace dda {

/** @brief Logical foreground service participating in request dispatch. */
enum class Service : uint8_t {
  None = 0U,          ///< No source or destination.
  CoilControl = 1U,   ///< Power-stage command service.
  SensorControl = 2U, ///< Sensor configuration and notification service.
  LaunchManager = 3U, ///< Launch acquisition and lifecycle service.
  UsbControl = 4U,    ///< USB host ingress or response egress.
  Safety = 5U,        ///< Board safety-state service.
  Count,              ///< Sentinel used to size the handler table.
};

/** @brief Cooperative lifecycle of one routed request. */
enum class RequestState : uint8_t {
  Idle = 0U, ///< Slot is unused.
  Incoming,  ///< Request is moving toward its destination service.
  Outgoing,  ///< Response is moving back toward its source service.
  Done,      ///< Processing finished and the slot may be reclaimed.
};

/** @brief Status values generated by routing policy rather than a service. */
enum class RequestStatus : uint8_t {
  Ok = 0U,                  ///< Request was not rejected by routing policy.
  BlockedDuringLaunch = 1U, ///< Competition-mode launch lockout rejected it.
};

/**
 * @brief Mutable request routed cooperatively between firmware services.
 * @details Timing fields contain raw 64 MHz TIM2 ticks. `createdAt` is set
 * when RequestManager accepts the request, `outgoingAt` when a response starts
 * its return path, and `doneAt` when the final service completes it. Unsigned
 * subtraction must be used so one TIM2 rollover is handled correctly.
 */
struct Request {
  Service destination{Service::None}; ///< Service to process the current leg.
  Service source{Service::None};      ///< Service that originated this leg.
  uint8_t command{0U};                ///< Service-specific command number.
  uint8_t options{0U};                ///< Command argument or response status.
  bool requiresAnswer{false};         ///< Whether to create a return leg.
  RequestState state{RequestState::Idle}; ///< Current routing lifecycle state.
  Service initialDestination{Service::None}; ///< Original measured service.
  uint8_t initialOptions{0U}; ///< Original argument retained for diagnostics.
  bool reachedOutgoing{false}; ///< Whether `outgoingAt` contains a timestamp.
  uint32_t createdAt{0U};      ///< TIM2 tick at manager acceptance.
  uint32_t outgoingAt{0U};     ///< TIM2 tick at service completion.
  uint32_t doneAt{0U};         ///< TIM2 tick at final completion.

  /**
   * @brief Complete the current leg or create the requested response leg.
   * @param completedBy Service completing the current request leg.
   */
  void complete(Service completedBy) noexcept;

private:
  friend class RequestManager;
  void accept(uint32_t timestamp) noexcept;
  void markOutgoing(uint32_t timestamp) noexcept;
};

/**
 * @brief Compact immutable diagnostic record for one completed request.
 * @details The 16-byte layout is serialized into debug-mode LaunchData. It
 * deliberately retains the original destination and options even when a
 * response changes the mutable Request fields.
 */
struct RequestSnapshot {
  /** @brief Flag indicating that `outgoingAt` is valid. */
  static constexpr uint8_t HasOutgoingTimestamp = 1U << 0U;

  uint32_t createdAt{0U};  ///< Manager-acceptance TIM2 tick.
  uint32_t outgoingAt{0U}; ///< Response-leg TIM2 tick, when flagged valid.
  uint32_t doneAt{0U};     ///< Final-completion TIM2 tick.
  Service service{Service::None}; ///< Original destination service.
  uint8_t command{0U};             ///< Original command number.
  uint8_t options{0U};             ///< Original request options.
  uint8_t flags{0U};               ///< Presence flags for optional fields.

  /** @brief Construct an empty wire record. */
  RequestSnapshot() noexcept = default;
  /**
   * @brief Capture immutable diagnostic fields from a completed request.
   * @param request Completed request to snapshot.
   */
  explicit RequestSnapshot(const Request &request) noexcept;
  /**
   * @brief Report whether `outgoingAt` contains a valid timestamp.
   * @return `true` when the response leg was reached.
   */
  bool hasOutgoingTimestamp() const noexcept {
    return (flags & HasOutgoingTimestamp) != 0U;
  }
};

static_assert(sizeof(RequestSnapshot) == 16U,
              "RequestSnapshot must remain a compact wire record");

/**
 * @brief Routes bounded foreground requests and records completion telemetry.
 * @details At most five requests are active concurrently. Completed requests
 * are copied into a 256-entry snapshot buffer until the next launch clears it.
 * LaunchManager exports those snapshots only in debug mode.
 */
class RequestManager {
public:
  /** @brief Maximum number of concurrently active requests. */
  static constexpr uint8_t Capacity = 5U;
  /** @brief Maximum number of retained completed-request snapshots. */
  static constexpr uint16_t SnapshotCapacity = 256U;

  /** @brief Construct an empty manager in competition mode. */
  RequestManager() noexcept;

  /**
   * @brief Register one service's `processRequest(Request&)` handler.
   * @tparam ServiceType Concrete service handler type.
   * @param service Logical service identifier to bind.
   * @param handler Process-lifetime handler instance.
   */
  template <typename ServiceType>
  void registerService(Service service, ServiceType &handler) noexcept {
    const uint8_t index = static_cast<uint8_t>(service);
    if ((service == Service::None) ||
        (index >= static_cast<uint8_t>(Service::Count))) {
      return;
    }
    _handlers[index] = {&handler, [](void *context, Request &request) noexcept {
                          static_cast<ServiceType *>(context)->processRequest(
                              request);
                        }};
  }

  /**
   * @brief Queue a request after applying launch-mode routing policy.
   * @param request Request value to copy into an active slot.
   * @return `true` when a slot accepted the request.
   */
  bool queueRequest(const Request &request) noexcept;
  /**
   * @brief Report whether another active request slot is available.
   * @return `true` when `queueRequest()` can accept a request.
   */
  bool hasCapacity() const noexcept;
  /** @brief Dispatch active requests and snapshot completed requests. */
  void process() noexcept;

  /** @brief Return the non-owning completed-snapshot array. @return Array. */
  const RequestSnapshot *snapshots() const noexcept { return _snapshots; }
  /** @brief Return valid entries in `snapshots()`. @return Snapshot count. */
  uint16_t snapshotCount() const noexcept { return _snapshotCount; }
  /** @brief Discard all retained diagnostic snapshots. */
  void clearSnapshots() noexcept;
  /**
   * @brief Remove active requests involving a service.
   * @param service Source or destination service to discard.
   */
  void discardRequestsInvolving(Service service) noexcept;

  /**
   * @brief Apply or release the launch-time routing policy.
   * @param active Whether a launch is active.
   */
  void setLaunchActive(bool active) noexcept;
  /** @brief Report launch-time routing state. @return Active state. */
  bool isLaunchActive() const noexcept;
  /** @brief Allow sensor notifications before a launch begins. */
  void unlockSensor() noexcept;
  /** @brief Report sensor-notification suppression. @return Block state. */
  bool isSensorBlocked() const noexcept;
  /**
   * @brief Select debug mode when enabled, competition mode otherwise.
   * @param enabled Whether debug behavior is selected.
   */
  void setDebugMode(bool enabled) noexcept;
  /** @brief Report selected competition mode. @return Competition state. */
  bool isCompetitionMode() const noexcept;

private:
  struct Handler {
    void *context;
    void (*process)(void *, Request &) noexcept;
  };

  void dispatchToServices() noexcept;
  void clearCompleted() noexcept;
  bool queueUnchecked(const Request &request) noexcept;
  bool blocksSensorNotification(const Request &request) const noexcept;
  bool blocksHostRequest(const Request &request) const noexcept;

  Request _requests[Capacity];
  RequestSnapshot _snapshots[SnapshotCapacity];
  Handler _handlers[static_cast<uint8_t>(Service::Count)];
  uint8_t _nextInsert;
  uint8_t _requestCount;
  uint16_t _snapshotCount;
  volatile bool _launchActive;
  volatile bool _sensorBlock;
  volatile bool _debugMode;
};

} // namespace dda
